name: .NET

on:
  push:
    branches: [ no-xamarin ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "SQLitePCL.raw"
    - uses: actions/checkout@v2
      with:
        repository: ericsink/cb
        path: "cb"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install workload ios
      run: dotnet workload install ios
    - name: Install workload maccatalyst
      run: dotnet workload install maccatalyst
    - name: Install workload tvos
      run: dotnet workload install tvos
    - name: Install T4
      run: dotnet tool install --global dotnet-t4
    - name: Build
      run: |
        cd SQLitePCL.raw/build
        dotnet run

