name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        # TODO want Linux here too, but the apple workloads aren't available there.
        os: [windows-2025, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "SQLitePCL.raw"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install T4
      run: dotnet tool install --global dotnet-t4
    - name: Build
      env:
        SG_NUGET_TOKEN: ${{ secrets.SG_NUGET_TOKEN }}
        SEE_ACTIVATION_CODE: ${{ secrets.SEE_ACTIVATION_CODE }}
      run: |
        cd SQLitePCL.raw/build
        dotnet run

