name: pub

on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: "SQLitePCL.raw"
    - uses: actions/checkout@v2
      with:
        repository: ericsink/cb
        path: "cb"
    - name: "Set up Java: 11"
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Install workload ios
      run: dotnet workload install ios
    - name: Install workload android
      run: dotnet workload install android
    - name: Install workload tvos
      run: dotnet workload install tvos
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install T4
      run: dotnet tool install --global dotnet-t4
    - name: Build
      run: |
        cd SQLitePCL.raw/build
        dotnet run
    - name: Push
      run: 
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      working-directory: SQLitePCL.raw/nupkgs

